### ISSUE TITLE
Optional C functions not supported anywhere but Windows.

### ISSUE THREAD

**Issue by sduensin** [Erick194/DoomRPG-RE#1]
It seems all the `*_s` optional C functions have never been implemented by anyone other than Microsoft.   This makes building difficult on other platforms.

**Comment by Erick194** [comment]
You are right, a few weeks ago I was working on the Linux version in Ubuntu, and I had to change all those functions, I am working on a modification of the code and identifying flags, soon I will make a commit with the code without those functions.

**Comment by jakubito** [comment]
Per Erick's request, I have opened #4 to fix this

**Comment by Erick194** [comment]
Excellent friend, thank you very much.
